#include "../Common.h"

struct PointLight
{
	float3 Color;
	float Intensity;
	float3 Pos;
	float Padding;
};

struct DirLight
{
	float3 Color;
	float Intensity;
	float3 Dir;
	float Padding;
};

struct LightData
{
	uint PointLightCount;
	uint DirLightCount;
	float2 Padding;
	PointLight PointLights[MAX_POINT_LIGHTS];
	DirLight DirLights[MAX_DIR_LIGHTS];
};

struct CameraData
{
	float4x4 View;
    float4x4 Proj;
	float4x4 InvViewProj;
    float3 Pos;
    float NearPlane;
	float3 Padding;
    float FarPlane;
};

struct GlobalBuffer
{
	LightData Lights;
	CameraData Camera;
	float3 SkyColor;
	float Time;
};

[[vk::binding(0, 0)]]
ConstantBuffer<GlobalBuffer> globalBuffer;

// Inverse-square law
float CalcAttenuation(float3 FragPos, float3 LightPos)
{
	float Distance = distance(FragPos, LightPos);
	return 1.f / (Distance * Distance);
}
