static const float PI = 3.14159265359f;

// Trowbridge-Reitz GGX normal distribution function
float DistributionGGX(float3 N, float3 H, float roughness)
{
	float a = roughness * roughness;
	float a2 = a * a;
	float NdotH = saturate(dot(N, H));
	float NdotH2 = NdotH * NdotH;

	float num = a2;
	float denum = (NdotH2 * (a2 - 1.f) + 1.f);
	denum = PI * denum * denum;

	return num / denum;
}

// F0 = specular reflectance at cosTheta == 1
float3 SchlickFresnel(float3 F0, float cosTheta)
{
	return F0 + (float3(1.f) - F0) * pow(1.f - cosTheta , 5.f);
}

// Smith Geometry function, using Schlick-GGX
float GeometrySmith(float3 N, float3 V, float3 L, float roughness)
{
	float NdotV = saturate(dot(N, V));
	float NdotL = saturate(dot(N, L));

	float ggx1 = GeometrySchlickGGX(NdotV, roughness);
	float ggx2 = GeometrySchlickGGX(NdotL, roughness);

	return ggx1 * ggx2;
}

float GeometrySchlickGGX(float NdotV, float roughness)
{
	float r = roughness + 1.f;
	float k = (r * r) / 8.f;

	float num = NdotV;
	float denum = NdotV * (1.f - k) + k;

	return num / denum;
}

// Ks is removed from the original equation since it's already accounted for in the Fresnel
void CookTorrenceBRDF(float3 N, float3 V, float3 L, float3 H, float3 albedo, float roughness, float metallic, out float3 outDiffuse, out float3 outSpecular)
{
	float D = DistributionGGX(N, H, roughness);

	float3 F0 = float3(0.04f);
	F0 = lerp(F0, albedo, metallic);
	float3 F = SchlickFresnel(F0, saturate(dot(H, V)));
	
	float G = GeometrySmith(N, V, L, roughness);

	float3 Ks = F;
	float3 Kd = float3(1.f, 1.f, 1.f) - Ks;
	Kd *= (1.f - metallic);

	outDiffuse = Kd * (albedo / PI);

	float NdotV = saturate(dot(N, V));
	float NdotL = saturate(dot(N, L));
	outSpecular = (D * F * G) / max(4.f * NdotV * NdotL, 0.001f); // protect against dividing by 0
}

float3 CalcLight(float3 N, float3 V, float3 L, float3 Li, float3 albedo, float roughness, float metallic)
{	
	float3 H = normalize(L + V); // halfway vector
	float NdotL = saturate(dot(N, L));
	float NdotH = saturate(dot(N, H));
	
	float3 diffuse, specular;
	CookTorrenceBRDF(N, V, L, H, albedo.rgb, roughness, metallic, diffuse, specular);
	float3 BRDF = diffuse + specular;

	float3 Lo = BRDF * Li * NdotL;
	return Lo;
}

static const float3x3 ACESInputMat =
{
	{ 0.59719, 0.35458, 0.04823 },
	{ 0.07600, 0.90834, 0.01566 },
	{ 0.02840, 0.13383, 0.83777 }
};

static const float3x3 ACESOutputMat =
{
	{  1.60475, -0.53108, -0.07367 },
	{ -0.10208,  1.10813, -0.00605 },
	{ -0.00327, -0.07276,  1.07602 }
};

float3 RRTAndODTFit(float3 color)
{
	float3 a = color * (color + 0.0245786f) - 0.000090537f;
	float3 b = color * (0.983729f * color + 0.4329510f) + 0.238081f;
	return a / b;
}

float3 HillACES(float3 color)
{
	float3 result = mul(ACESInputMat, color);
	result = RRTAndODTFit(result);
	result = mul(ACESOutputMat, result);

	return saturate(result);
}

float HenyeyGreenstein(float cosTheta, float g)
{
    float g2 = g * g;
    float denom = 1.f + g2 - 2.f * g * cosTheta;
    return (1.f - g2) / (4.f * PI * pow(max(denom, 0.0001f), 1.5f));
}
